### ISSUE TITLE
Annotations archive is corrupt - missing folder video-lists

### ISSUE THREAD

**Issue by AustinCStone** [TAO-Dataset/annotations#1]
It appears there are missing files in the annotations archive. To reproduce this error:

Download the annotations:
```bash
wget https://github.com/TAO-Dataset/annotations/archive/v1.1.tar.gz
```
Run the following python segment to attempt to extract each file in the archive:
```python
import tarfile
with open('v1.1.tar.gz.1', 'rb') as fobj:
    tar = tarfile.open(mode='r:*', fileobj=fobj)
    for member in tar:
        extract_file = tar.extractfile(member)
```
This will ead the the following error:
```
KeyError: "linkname 'annotations-1.1/video-lists/../../video-lists/README.md' not found"
```

Similarly, if you just extract the archive using:

```bash
tar -xvf v1.1.tar.gz 
```

Everything will extract, but all files under the video-lists directory will be empty. Try doing this and then opening:

```bash
vi annotations-1.1/video-lists/tao_charades.txt
```

**Comment by achalddave** [comment]
D'oh, my bad. Looks like I added symlinks into the archive instead of the symlinked files contents. I'll update the annotations in about a day. Thanks for filing this issue! In the meantime, the correct files are available in this repo.

**Comment by AustinCStone** [comment]
Thanks :) Could you please post back here once the annotations are updated? (I'm trying to add the dataset to [TFDS](https://www.tensorflow.org/datasets/api_docs/python/tfds) which requires a downloadable link)

**Comment by achalddave** [comment]
Just pushed a new release: https://github.com/TAO-Dataset/annotations/releases/tag/v1.2

This direct link should work: https://github.com/TAO-Dataset/annotations/archive/v1.2.tar.gz. Let me know if not!
